### ISSUE TITLE
Metadata file Csla.Analyzers.dll could not be found

### ISSUE THREAD

**Issue by pecen** [MarimerLLC/cslaforum#56]
I recently switched to VS 2015 (from VS 2013), and in my current Project I now get the error message "Metadata file '..\packages\CSLA-Core.4.6.100\analyzers\c#\Csla.Analyzers.dll' could not be found" for my .Dal-, .DalSql-, and .Library Projects, and it won't compile. Of course I could go back to VS 2013 temporarily, but I would rather like to solve this for VS 2015. I understand that one of the new features in VS 2015 is some kind of analyzer for the Projects in my solution, but how do I fix it to work with my current Project?

Thanks,
Peter Centellini

**Comment by JasonBock** [comment]
@rockfordlhotka and I have had a "fun" time getting analyzers to work correctly with Nuget. We thought we fixed them all, but apparently not. I just made a simple class library project, referenced Csla from Nuget, and the analyzers installed and worked fine.

When you say you get the error message and the projects won't compile, what compilation errors are you seeing? What do you see when you look in the Analyzers node under the References node of your project(s)?

**Comment by pecen** [comment]
Yeah, I can just imagine the "fun". 
Anyway, don't know what happened but after opening the solution in VS2013, recompiling, and then open it in VS2015 again, I get no errors. 

The solution consists of a .Dal-, .DalSql-, .Lib-, 2 different MVC5-projects with Kendo UI (Telerik), and a Telerik WinForm Project. All according to the Encapsulated Invoke Dto-model described in the "Using CSLA 4" e-book series. 

It's only the Dal and Business tier Projects that failed. But as I said, it seems to work all of a sudden. 

If you use the link below you can see a screenshot of how it looks in the Analyzers node under the References node in 2 of the 3 before failing Projects. It looks like there is a warning Icon although it works to compile.

![capture](https://cloud.githubusercontent.com/assets/4786821/9881556/30bd5d48-5bd9-11e5-8051-3ac263cc8687.PNG)

**Comment by pecen** [comment]
...I forgot to say that the path that is not fully shown in the Picture above is:
D:\Projekt\Sandbox\CarRentalCSLA\Main\src\packages\CSLA-Core.4.6.100\analyzers\c#\Csla.Analyzers.dll, so it obviously still is something with the Csla.Analyzers.dll.

**Comment by rockfordlhotka** [comment]
You may want to (if you can) try the 4.6.171 prerelease where we are testing fixes for some of these issues. At the moment I think we have the *errors* resolved, but are still getting warnings about the analyzers during build.

**Comment by pecen** [comment]
Ok, thanks. I will try that.

**Comment by rockfordlhotka** [comment]
I just pushed 4.6.172-Beta to NuGet, but I think there are no analyzer changes from 171.

Please let us know if you see any improvement.

**Comment by lmsantin** [comment]
Yesterday I created a new project and installed the CSLA current version in Nuget(Latest stable 4.6.100) and I am getting the analyzers warnings.

**Comment by JasonBock** [comment]
Do the analyzers work though?

**Comment by rockfordlhotka** [comment]
btw @JasonBock , here are the warnings I get (per-project in my solution) when I build:

```
1>CSC : warning CS8032: An instance of analyzer Csla.Analyzers.FindSaveAssignmentIssueAnalyzer cannot be created from C:\Users\rocky\Documents\GitHub\rockfordlhotka\csla\Samples\ProjectTracker\packages\CSLA-Core.4.6.173-Beta\analyzers\c#\Csla.Analyzers.dll : Could not load file or assembly 'System.Collections.Immutable, Version=1.1.37.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..
1>CSC : warning CS8032: An instance of analyzer Csla.Analyzers.EvaluatePropertiesForSimplicityAnalyzer cannot be created from C:\Users\rocky\Documents\GitHub\rockfordlhotka\csla\Samples\ProjectTracker\packages\CSLA-Core.4.6.173-Beta\analyzers\c#\Csla.Analyzers.dll : Could not load file or assembly 'System.Collections.Immutable, Version=1.1.37.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..
1>CSC : warning CS8032: An instance of analyzer Csla.Analyzers.IsOperationMethodPublicAnalyzer cannot be created from C:\Users\rocky\Documents\GitHub\rockfordlhotka\csla\Samples\ProjectTracker\packages\CSLA-Core.4.6.173-Beta\analyzers\c#\Csla.Analyzers.dll : Could not load file or assembly 'System.Collections.Immutable, Version=1.1.37.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..
1>CSC : warning CS8032: An instance of analyzer Csla.Analyzers.CheckConstructorsAnalyzer cannot be created from C:\Users\rocky\Documents\GitHub\rockfordlhotka\csla\Samples\ProjectTracker\packages\CSLA-Core.4.6.173-Beta\analyzers\c#\Csla.Analyzers.dll : Could not load file or assembly 'System.Collections.Immutable, Version=1.1.37.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..
1>CSC : warning CS8032: An instance of analyzer Csla.Analyzers.IsBusinessObjectSerializableAnalyzer cannot be created from C:\Users\rocky\Documents\GitHub\rockfordlhotka\csla\Samples\ProjectTracker\packages\CSLA-Core.4.6.173-Beta\analyzers\c#\Csla.Analyzers.dll : Could not load file or assembly 'System.Collections.Immutable, Version=1.1.37.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..
```

**Comment by lmsantin** [comment]
I am getting the same in my solution

**Comment by rockfordlhotka** [comment]
Just released an update to the 4.6.173 beta (via NuGet). This update _should_ fix the warnings with the analyzers - please let us know on the cslaforum at GitHub if you are still having issues.

**Comment by JasonBock** [comment]
Confirmed that it got rid of the warnings - w00t!

**Comment by GudAnuf** [comment]
HI
I Just Updated to 4.6.2 and am getting the following analyzer warning:

Message	AD0001	The User Diagnostic Analyzer 'Csla.Analyzers.EvaluatePropertiesForSimplicityAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	EPS.Library		1	IntelliSense

**Comment by JasonBock** [comment]
@GudAnuf can you please make a new issue to specifically address this issue? Thanks :)

**Comment by pecen** [comment]
Hi,
In the project I'm currently in, I'm using CSLA for the business tier part, i.e. creating business objects (Library classes) that inherits from BusinessBase/ReadonlyBase/ReadonlyListbase etc, together with the usual DAL-part with Dto's. Anyway, after finishing off my current feature branch (git/sourcetree), where it's merged with the develop branch, our build servers now get the error mentioned in this thread, i.e.:

CSC : error CS0006: Metadata file '..\packages\CSLA-Core.4.7.101\analyzers\c#
\Csla.Analyzers.dll' could not be found [d:\GitRepos\Domino\ETC.Accounting.Hogi
a\ETC.Accounting.Hogia.csproj]

Any suggestion?

Thanks,
Peter

**Comment by tfreitasleal** [comment]
Hi Peter,

When I get thsi error, usually that's because there is a package path mismatch. I hand edited the csproj file [I know we shouldn't do it at home :) ] and changed either the Csla version or the target framework. The search & replace missed the analyser part.

Usual fix is: remove Csla-core package and add it again.

**Comment by pecen** [comment]
Hi Tiago,

Thanks for your answer. In this case I haven't hand edited the .csproj file, but I will have a look at it, and see if the remove/add will help. But just to be clear, I don't have the problem locally on my dev computer. This occured after the feature branch was finished by me (git flow), and merged with the develop branch. When a build was created on the build server later, this error stopped the build process.
